### ISSUE TITLE
Wrong prometheus endpoint?

### ISSUE THREAD

**Issue by katopz** [vfarcic/docker-flow-stacks#9]
After deploy [prometheus-grafana-df-proxy.yml](https://github.com/vfarcic/docker-flow-stacks/blob/master/metrics/prometheus-grafana-df-proxy.yml)

I found that at page `http://localhost:9091/targets`  
has prometheus endpoint  
`http://localhost:9090/metrics`  
but it link to  
`http://b1b1472b3e3e:9090/metrics`
which look like node id instead of node ip.

![image](https://cloud.githubusercontent.com/assets/97060/26390266/118b1dbc-4088-11e7-9d20-fc38153ec80c.png)

And actually it should be `http://localhost:9091/metrics`? (It did print output fine at 9091)

Thanks

**Comment by vfarcic** [comment]
The address should be localhost:9090 since that's the port Prometheus is listening to. 9091 is the mapping for the requests coming from outside the container. Since the target looks for localhost, it should be the internal port 9090.

I did notice the same error before but it disappeared a bit later when it tried to scrape it again. Can you double check that's not your case?

I rerun that stack a few minutes ago and go everything green. If in your case prometheus endpoint continues being red after a while (give it a few minutes just in case), we should try to figure out what's the difference between my system and yours.

**Comment by katopz** [comment]
For some reason it's appear all green now after remove all node and redo all over again, I can't tell what go wrong there because I try too many thing at that time even reinstall docker and also restart.

One thing I notice is Docker somehow provide different IP after many **remove all nodes** and retry, usually it always like...

node-1 = `192.168.99.100`
node-2 = `192.168.99.101`
node-3 = `192.168.99.102`

but somehow it was like...

node-1 = `192.168.99.106`
node-2 = `192.168.99.107`
node-3 = `192.168.99.108`

And start to have [this issue](https://github.com/docker/kitematic/issues/1193#issuecomment-227566497) (and solved by that comment) in between.

I'll close this in case for now in case I can't reproduce it any more.

Thanks
